name: Documentation

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install doxygen
    - name: Build
      run: doxygen
    - uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: docs
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: ./docs/html
        commit-message: Deploy to GitHub Pages
