name: Documentation

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install doxygen
    - name: Build
      run: doxygen
    - uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: docs
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
